import { Hono } from "npm:hono";
import { initDatabase, sqlite } from "../lib/db.ts";
import { requireAuth } from "./middleware.ts";

const router=new Hono();
const slugify=(v:string)=>v.trim().toLowerCase().normalize("NFKD").replace(/[^a-z0-9\s-]/g,"").replace(/[\s_-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);
const error=(c:any,s:number,code:string,message:string)=>c.json({error:{code,message}},s);
const validName=(b:any)=>typeof b?.name==="string"&&b.name.trim().length>0;

router.get("/categories",async c=>{await initDatabase();return c.json({data:(await sqlite.execute("SELECT * FROM categories ORDER BY name")).rows});});
router.get("/tags",async c=>{await initDatabase();return c.json({data:(await sqlite.execute("SELECT * FROM tags ORDER BY name")).rows});});
router.get("/technologies",async c=>{await initDatabase();return c.json({data:(await sqlite.execute("SELECT * FROM technologies ORDER BY name")).rows});});
router.get("/tags/:slug/posts",async c=>{await initDatabase();const tag=(await sqlite.execute("SELECT id,name,slug FROM tags WHERE slug=? LIMIT 1",[c.req.param("slug")])).rows[0] as any;if(!tag)return error(c,404,"TAG_NOT_FOUND","Tag not found.");const rows=await sqlite.execute("SELECT p.id,p.title,p.slug,p.description,p.content_type,p.published_at,p.reading_time,(SELECT GROUP_CONCAT(c.name, ', ') FROM categories c JOIN post_categories pc ON pc.category_id=c.id WHERE pc.post_id=p.id) AS category_name FROM posts p JOIN post_tags pt ON pt.post_id=p.id WHERE p.status = 'published' AND pt.tag_id=? ORDER BY p.published_at DESC",[tag.id]);return c.json({data:{tag,posts:rows.rows}});});

router.post("/categories",requireAuth,async c=>{await initDatabase();const b=await c.req.json().catch(()=>({}));if(!validName(b))return error(c,400,"INVALID_NAME","Name is required.");const n=b.name.trim(),s=slugify(b.slug||n);try{await sqlite.execute("INSERT INTO categories(name,slug,description) VALUES(?,?,?)",[n,s,b.description?.trim()||null]);return c.json({data:(await sqlite.execute("SELECT * FROM categories WHERE slug=?",[s])).rows[0]},201);}catch{return error(c,409,"CATEGORY_EXISTS","Category name or slug already exists.");}});
router.put("/categories/:id",requireAuth,async c=>{await initDatabase();const id=Number(c.req.param("id"));const o=(await sqlite.execute("SELECT * FROM categories WHERE id=?",[id])).rows[0] as any;if(!o)return error(c,404,"NOT_FOUND","Category not found.");const b=await c.req.json().catch(()=>({}));const n=String(b.name??o.name).trim(),s=slugify(String(b.slug??o.slug));try{await sqlite.execute("UPDATE categories SET name=?,slug=?,description=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[n,s,b.description??o.description,id]);return c.json({data:(await sqlite.execute("SELECT * FROM categories WHERE id=?",[id])).rows[0]});}catch{return error(c,409,"CATEGORY_EXISTS","Category name or slug already exists.");}});
router.delete("/categories/:id",requireAuth,async c=>{await initDatabase();const r=await sqlite.execute("DELETE FROM categories WHERE id=?",[Number(c.req.param("id"))]);if(!(r as any).rowsAffected)return error(c,404,"NOT_FOUND","Category not found.");return c.json({data:{deleted:true}});});

router.post("/tags",requireAuth,async c=>{await initDatabase();const b=await c.req.json().catch(()=>({}));if(!validName(b))return error(c,400,"INVALID_NAME","Name is required.");const n=b.name.trim(),s=slugify(b.slug||n);try{await sqlite.execute("INSERT INTO tags(name,slug) VALUES(?,?)",[n,s]);return c.json({data:(await sqlite.execute("SELECT * FROM tags WHERE slug=?",[s])).rows[0]},201);}catch{return error(c,409,"TAG_EXISTS","Tag name or slug already exists.");}});
router.put("/tags/:id",requireAuth,async c=>{await initDatabase();const id=Number(c.req.param("id"));const o=(await sqlite.execute("SELECT * FROM tags WHERE id=?",[id])).rows[0] as any;if(!o)return error(c,404,"NOT_FOUND","Tag not found.");const b=await c.req.json().catch(()=>({}));const n=String(b.name??o.name).trim(),s=slugify(String(b.slug??o.slug));try{await sqlite.execute("UPDATE tags SET name=?,slug=? WHERE id=?",[n,s,id]);return c.json({data:(await sqlite.execute("SELECT * FROM tags WHERE id=?",[id])).rows[0]});}catch{return error(c,409,"TAG_EXISTS","Tag name or slug already exists.");}});
router.delete("/tags/:id",requireAuth,async c=>{await initDatabase();const r=await sqlite.execute("DELETE FROM tags WHERE id=?",[Number(c.req.param("id"))]);if(!(r as any).rowsAffected)return error(c,404,"NOT_FOUND","Tag not found.");return c.json({data:{deleted:true}});});

router.post("/technologies",requireAuth,async c=>{await initDatabase();const b=await c.req.json().catch(()=>({}));if(!validName(b))return error(c,400,"INVALID_NAME","Name is required.");const n=b.name.trim(),s=slugify(b.slug||n);try{await sqlite.execute("INSERT INTO technologies(name,slug,description,website_url,logo_url) VALUES(?,?,?,?,?)",[n,s,b.description?.trim()||null,b.website_url?.trim()||null,b.logo_url?.trim()||null]);return c.json({data:(await sqlite.execute("SELECT * FROM technologies WHERE slug=?",[s])).rows[0]},201);}catch{return error(c,409,"TECHNOLOGY_EXISTS","Technology name or slug already exists.");}});
router.put("/technologies/:id",requireAuth,async c=>{await initDatabase();const id=Number(c.req.param("id"));const o=(await sqlite.execute("SELECT * FROM technologies WHERE id=?",[id])).rows[0] as any;if(!o)return error(c,404,"NOT_FOUND","Technology not found.");const b=await c.req.json().catch(()=>({}));const n=String(b.name??o.name).trim(),s=slugify(String(b.slug??o.slug));try{await sqlite.execute("UPDATE technologies SET name=?,slug=?,description=?,website_url=?,logo_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[n,s,b.description??o.description,b.website_url??o.website_url,b.logo_url??o.logo_url,id]);return c.json({data:(await sqlite.execute("SELECT * FROM technologies WHERE id=?",[id])).rows[0]});}catch{return error(c,409,"TECHNOLOGY_EXISTS","Technology name or slug already exists.");}});
router.delete("/technologies/:id",requireAuth,async c=>{await initDatabase();const r=await sqlite.execute("DELETE FROM technologies WHERE id=?",[Number(c.req.param("id"))]);if(!(r as any).rowsAffected)return error(c,404,"NOT_FOUND","Technology not found.");return c.json({data:{deleted:true}});});

export const taxonomy=router;
